### ISSUE TITLE
Spawned Tome shows Blank Rectangle when original Tome is stuck

### ISSUE THREAD

**Issue by Shadowrs** [EccentricVamp/EccentricTome#33]
**Versions**
 - Minecraft: 1.18.2
 - Eccentric Tome eccentrictome-1.18.2-1.8.0 Forge
 - ATM7 modpack, 200 mods with like 20 manuals/books/guides

**Describe the bug**
When right clicking the book in the action bar, it doesnt open book selection, instead its a small empty rectangle box in the middle of the screen

**To Reproduce**
It started off working, I opened Industrial Forgoing's Manual - but shift/ctrl right clicking doesnt make it revert back to the Eccentric Tome. It's stuck. Now I spawned a new Tome, and thats blank

**Expected behavior**
- Shift right click reverts Manual back to Tome
- Whatever that rectangle is/open tome as usual

**Screenshots**
![alt](https://i.imgur.com/xdHS2Hf.png)
![alt](https://i.imgur.com/Neu5EEi.png)

**Additional context**
Full log https://pastebin.com/FfB7gw8f
log has 2 exceptions. both look like they deal with books.

```
[11:28:18] [Render thread/ERROR]: Error loading extending book rftoolsbase:manual with addon book deepresonance:manual, skipping
com.google.gson.JsonSyntaxException: Expected sortnum to be a Int, was "9"
	at net.minecraft.util.GsonHelper.m_13897_(GsonHelper.java:254) ~[client-1.18.2-20220404.173914-srg.jar%23391!/:?]
	at net.minecraft.util.GsonHelper.m_13824_(GsonHelper.java:268) ~[client-1.18.2-20220404.173914-srg.jar%23391!/:?]
	at vazkii.patchouli.client.book.BookCategory.<init>(BookCategory.java:56) ~[Patchouli-1.18.2-71.1.jar%23290!/:1.18.2-71.1]
	at vazkii.patchouli.client.book.BookContentsBuilder.loadCategory(BookContentsBuilder.java:150) ~[Patchouli-1.18.2-71.1.jar%23290!/:1.18.2-71.1]
```

```[11:28:19] [Render thread/ERROR]: Error compiling book twilightforest:guide, using empty contents
java.lang.RuntimeException: Error building entry twilightforest:world/portal
	at vazkii.patchouli.client.book.BookContentsBuilder.lambda$build$2(BookContentsBuilder.java:98) ~[Patchouli-1.18.2-71.1.jar%23290!/:1.18.2-71.1]
	at java.util.HashMap$Values.forEach(HashMap.java:1065) ~[?:?]
	at vazkii.patchouli.client.book.BookContentsBuilder.build(BookContentsBuilder.java:94) ~[Patchouli-1.18.2-71.1.jar%23290!/:1.18.2-71.1]
	at vazkii.patchouli.common.book.Book.reloadContents(Book.java:225) ~[Patchouli-1.18.2-71.1.jar%23290!/:1.18.2-71.1]
	at vazkii.patchouli.common.book.BookRegistry.reloadContents(BookRegistry.java:128) ~[Patchouli-1.18.2-71.1.jar%23290!/:1.18.2-71.1]
	at vazkii.patchouli.client.book.ClientBookRegistry.reload(ClientBookRegistry.java:63) ~[Patchouli-1.18.2-71.1.jar%23290!/:1.18.2-71.1]
	at vazkii.patchouli.client.base.ClientAdvancements.onClientPacket(ClientAdvancements.java:34) ~[Patchouli-1.18.2-71.1.jar%23290!/:1.18.2-71.1]
	at net.minecraft.client.multiplayer.ClientAdvancements.handler$cdp000$patchouli_onSync(ClientAdvancements.java:1017) ~[client-1.18.2-20220404.173914-srg.jar%23391!/:?]
	at net.minecraft.client.multiplayer.ClientAdvancements.m_104399_(ClientAdvancements.java:57) ~[client-1.18.2-20220404.173914-srg.jar%23391!/:?]
	at net.minecraft.client.multiplayer.ClientPacketListener.m_5498_(ClientPacketListener.java:1135) ~[client-1.18.2-20220404.173914-srg.jar%23391!/:?]
	at net.minecraft.network.protocol.game.ClientboundUpdateAdvancementsPacket.m_5797_(ClientboundUpdateAdvancementsPacket.java:51) ~[client-1.18.2-20220404.173914-srg.jar%23391!/:?]
	at net.minecraft.network.protocol.game.ClientboundUpdateAdvancementsPacket.m_5797_(ClientboundUpdateAdvancementsPacket.java:16) ~[client-1.18.2-20220404.173914-srg.jar%23391!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[client-1.18.2-20220404.173914-srg.jar%23391!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.18.2-20220404.173914-srg.jar%23391!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.18.2-20220404.173914-srg.jar%23391!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.18.2-20220404.173914-srg.jar%23391!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[client-1.18.2-20220404.173914-srg.jar%23391!/:?]
	at jeresources.util.LootTableHelper.getLootTables(LootTableHelper.java:187) ~[JustEnoughResources-1.18.2-0.14.1.171.jar%23228!/:0.14.1.171]
	at jeresources.compatibility.minecraft.MinecraftCompat.registerVanillaMobs(MinecraftCompat.java:42) ~[JustEnoughResources-1.18.2-0.14.1.171.jar%23228!/:0.14.1.171]
	at jeresources.compatibility.minecraft.MinecraftCompat.init(MinecraftCompat.java:34) ~[JustEnoughResources-1.18.2-0.14.1.171.jar%23228!/:0.14.1.171]
	at jeresources.compatibility.Compatibility.init(Compatibility.java:26) ~[JustEnoughResources-1.18.2-0.14.1.171.jar%23228!/:0.14.1.171]
	at jeresources.proxy.CommonProxy.initCompatibility(CommonProxy.java:14) ~[JustEnoughResources-1.18.2-0.14.1.171.jar%23228!/:0.14.1.171]
	at jeresources.jei.JEIConfig.registerCategories(JEIConfig.java:91) ~[JustEnoughResources-1.18.2-0.14.1.171.jar%23228!/:0.14.1.171]
	at mezz.jei.load.PluginLoader.lambda$createRecipeCategories$3(PluginLoader.java:133) ~[jei-1.18.2-9.7.2.266.jar%23223!/:9.7.2.266]
	at mezz.jei.load.PluginCaller.callOnPlugins(PluginCaller.java:26) ~[jei-1.18.2-9.7.2.266.jar%23223!/:9.7.2.266]
	at mezz.jei.load.PluginLoader.createRecipeCategories(PluginLoader.java:133) ~[jei-1.18.2-9.7.2.266.jar%23223!/:9.7.2.266]
	at mezz.jei.load.PluginLoader.createRecipeManager(PluginLoader.java:159) ~[jei-1.18.2-9.7.2.266.jar%23223!/:9.7.2.266]
	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:129) ~[jei-1.18.2-9.7.2.266.jar%23223!/:9.7.2.266]
	at mezz.jei.forge.startup.ClientLifecycleHandler.startJei(ClientLifecycleHandler.java:112) ~[jei-1.18.2-9.7.2.266.jar%23223!/:9.7.2.266]
	at mezz.jei.forge.startup.StartEventObserver.transitionState(StartEventObserver.java:143) ~[jei-1.18.2-9.7.2.266.jar%23223!/:9.7.2.266]
	at mezz.jei.forge.startup.StartEventObserver.onEvent(StartEventObserver.java:106) ~[jei-1.18.2-9.7.2.266.jar%23223!/:9.7.2.266]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraft.client.multiplayer.ClientPacketListener.m_5859_(ClientPacketListener.java:1270) ~[client-1.18.2-20220404.173914-srg.jar%23391!/:?]
	at net.minecraft.network.protocol.game.ClientboundUpdateTagsPacket.m_5797_(ClientboundUpdateTagsPacket.java:35) ~[client-1.18.2-20220404.173914-srg.jar%23391!/:?]
	at net.minecraft.network.protocol.game.ClientboundUpdateTagsPacket.m_5797_(ClientboundUpdateTagsPacket.java:11) ~[client-1.18.2-20220404.173914-srg.jar%23391!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[client-1.18.2-20220404.173914-srg.jar%23391!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.18.2-20220404.173914-srg.jar%23391!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.18.2-20220404.173914-srg.jar%23391!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.18.2-20220404.173914-srg.jar%23391!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[client-1.18.2-20220404.173914-srg.jar%23391!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1015) ~[client-1.18.2-20220404.173914-srg.jar%23391!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665) ~[client-1.18.2-20220404.173914-srg.jar%23391!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23391!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.80.jar%2317!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
Caused by: java.lang.RuntimeException: Error while loading entry twilightforest:world/portal page 2
	at vazkii.patchouli.client.book.BookEntry.build(BookEntry.java:250) ~[Patchouli-1.18.2-71.1.jar%23290!/:1.18.2-71.1]
	at vazkii.patchouli.client.book.BookContentsBuilder.lambda$build$2(BookContentsBuilder.java:96) ~[Patchouli-1.18.2-71.1.jar%23290!/:1.18.2-71.1]
	... 58 more
Caused by: java.lang.RuntimeException: Malformed item ID 
	at vazkii.patchouli.common.util.ItemStackUtil.parseItemStackString(ItemStackUtil.java:78) ~[Patchouli-1.18.2-71.1.jar%23290!/:1.18.2-71.1]
	at vazkii.patchouli.common.util.ItemStackUtil.loadStackFromString(ItemStackUtil.java:114) ~[Patchouli-1.18.2-71.1.jar%23290!/:1.18.2-71.1]
	at vazkii.patchouli.common.util.ItemStackUtil.loadStackListFromString(ItemStackUtil.java:147) ~[Patchouli-1.18.2-71.1.jar%23290!/:1.18.2-71.1]
	at vazkii.patchouli.common.util.ItemStackUtil.loadIngredientFromString(ItemStackUtil.java:128) ~[Patchouli-1.18.2-71.1.jar%23290!/:1.18.2-71.1]
	at vazkii.patchouli.client.book.template.variable.IngredientVariableSerializer.fromJson(IngredientVariableSerializer.java:13) ~[Patchouli-1.18.2-71.1.jar%23290!/:1.18.2-71.1]
	at vazkii.patchouli.client.book.template.variable.IngredientVariableSerializer.fromJson(IngredientVariableSerializer.java:10) ~[Patchouli-1.18.2-71.1.jar%23290!/:1.18.2-71.1]
	at vazkii.patchouli.client.book.template.variable.Variable.as(Variable.java:31) ~[Patchouli-1.18.2-71.1.jar%23290!/:1.18.2-71.1]
	at vazkii.patchouli.client.book.page.PageSpotlight.build(PageSpotlight.java:29) ~[Patchouli-1.18.2-71.1.jar%23290!/:1.18.2-71.1]
	at vazkii.patchouli.client.book.BookEntry.build(BookEntry.java:247) ~[Patchouli-1.18.2-71.1.jar%23290!/:1.18.2-71.1]
	at vazkii.patchouli.client.book.BookContentsBuilder.lambda$build$2(BookContentsBuilder.java:96) ~[Patchouli-1.18.2-71.1.jar%23290!/:1.18.2-71.1]
	... 58 more```

**Comment by Shadowrs** [comment]
Was actually working as intended - somehow I lost all the books inside and so its empty 
also left clicked air (a long way away from any close dirt) and it reverted correctly
